spring:
  application:
    name: digital-banking

  cloud:
    openfeign:
      client:
        config:
          core-accounts:
            url: http://localhost:8500/api
          dummy-transfer:
            url: http://localhost:8502/api


server:
  port: 8501
  servlet:
    context-path: /api