spring:
  application:
    name: core-banking


server:
  port: 8500
  servlet:
    context-path: /api


management:
  endpoints:
    web:
      exposure:
        include: health
#        include: health,prometheus
  otlp:
    metrics:
      export:
#        url: http://localhost:4318/v1/metrics
        step: 10s